### ISSUE TITLE
set_tokens doesnt work with multi-line input

### ISSUE THREAD

**Issue by isidentical** [isidentical/pepgrave#1]
## Input
```elm
greet name = 
  name
```
## Transformer
```py
    @pattern("name", "name", "equal", "newline", "*indent", "name", "newline")
    def elm_function_resolver(self, *tokens):
        function_name, argument, *_, return_value, __ = tokens
        return self.quick_tokenize(f"{function_name.string} = (lambda {argument.string}: {return_value.string})")
```
## Output
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/isidentical/pepgrave/pepgrave/__main__.py", line 22, in <module>
    main(sys.argv)
  File "/home/isidentical/pepgrave/pepgrave/__main__.py", line 17, in main
    result = flint(file_contents)
  File "/home/isidentical/pepgrave/pepgrave/flint.py", line 120, in flint
    source = token_transformer.transform(source)
  File "/home/isidentical/pepgrave/pepgrave/flint.py", line 83, in transform
    super().transform(source)
  File "/home/isidentical/pepgrave/pepgrave/transformers.py", line 286, in transform
    stream_tokens_buffer = self._pattern_transformer_regex(
  File "/home/isidentical/pepgrave/pepgrave/transformers.py", line 239, in _pattern_transformer_regex
    stream_tokens = self._slice_replace(visitor, slices, stream_tokens)
  File "/home/isidentical/pepgrave/pepgrave/transformers.py", line 183, in _slice_replace
    tokens = visitor(*matching_tokens) or matching_tokens
  File "/home/isidentical/pepgrave/pepgrave/flint.py", line 106, in context_finder
    self.source = pep.resolver.transform(
  File "/home/isidentical/pepgrave/pepgrave/transformers.py", line 291, in transform
    source = tokenize.untokenize(stream_tokens)
  File "/usr/lib/python3.8/tokenize.py", line 278, in untokenize
    out = ut.untokenize(iterable)
  File "/usr/lib/python3.8/tokenize.py", line 212, in untokenize
    self.add_whitespace(start)
  File "/usr/lib/python3.8/tokenize.py", line 173, in add_whitespace
    raise ValueError("start ({},{}) precedes previous end ({},{})"
ValueError: start (1,0) precedes previous end (4,0)
```
## Reason
https://github.com/isidentical/pepgrave/blob/22f699d7795e03ab31ab36dab89454dfd4c50d7b/pepgrave/transformers.py#L298-L302

**Comment by isidentical** [comment]
Solutions;
  - creating a new untokenizer which will automate this process (working on)
  - re-design set_tokens with a line-based approach
  - after all tokens replaced auto-positioning the wrong ones (padder branch, last resort)
